title: Runpeng (John) Luo
url: "https://runpengluo.github.io"
baseurl: "/runpengluo"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Built with Jekyll, using the Researcher theme."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/runpengluo/"
 - name: "Resume"
   link: "resume"
 - name: "Publications"
   link: "publications"
 - name: "Contact"
   link: "contact"
