#!/usr/bin/env python3
# Fetch visitor counts per country from GoatCounter into _data/visitors.yml.
#
# Runpeng Luo (2026-08-02)
#
# Dependencies:
#   python3 (stdlib only)
#
# Usage:
#   GOATCOUNTER_TOKEN=... python3 scripts/fetch_visitors.py [site] [start]
#           site     # GoatCounter site code, default "runpengluo"
#           start    # first day to count from, default 2020-01-01
#
# Inputs
#   GOATCOUNTER_TOKEN: API token with "read statistics" permission
# Outputs:
#   _data/visitors.yml: updated date, total visitors, countries sorted by count
# Notes/References:
#   GET /api/v0/stats/locations returns {"stats": [{"id", "name", "count"}], "more"}
#   where id is an ISO 3166-1 alpha-2 code. https://www.goatcounter.com/api

import datetime
import json
import os
import sys
import urllib.error
import urllib.request

PAGE_LIMIT = 200
MAX_PAGES = 10
OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "_data", "visitors.yml")


def fetch_page(site, token, start, offset):
    """Request one page of location stats.

    Args:
        site: GoatCounter site code.
        token: API token sent as a bearer token.
        start: First day to include, as YYYY-MM-DD.
        offset: Pagination offset.

    Returns:
        Tuple of (list of stat dicts, whether more pages follow).
    """
    url = "https://%s.goatcounter.com/api/v0/stats/locations?start=%s&limit=%d&offset=%d" % (
        site,
        start,
        PAGE_LIMIT,
        offset,
    )
    req = urllib.request.Request(url, headers={"Authorization": "Bearer " + token})
    with urllib.request.urlopen(req, timeout=30) as resp:
        body = json.load(resp)
    return body.get("stats", []), bool(body.get("more"))


def yaml_quote(value):
    return '"%s"' % str(value).replace("\\", "\\\\").replace('"', '\\"')


def write_yaml(path, countries, updated):
    total = sum(c["count"] for c in countries)
    lines = [
        "# Generated by scripts/fetch_visitors.py -- do not edit by hand.",
        "updated: %s" % updated,
        "total: %d" % total,
        "countries:",
    ]
    for c in countries:
        lines.append("  - code: %s" % yaml_quote(c["id"]))
        lines.append("    name: %s" % yaml_quote(c["name"]))
        lines.append("    count: %d" % c["count"])
    if not countries:
        lines[-1] = "countries: []"
    with open(path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("wrote %s: %d countries, %d visitors" % (path, len(countries), total))


def main():
    token = os.environ.get("GOATCOUNTER_TOKEN", "").strip()
    if not token:
        sys.exit("GOATCOUNTER_TOKEN is not set")
    site = sys.argv[1] if len(sys.argv) > 1 else "runpengluo"
    start = sys.argv[2] if len(sys.argv) > 2 else "2020-01-01"

    countries, offset = [], 0
    for _ in range(MAX_PAGES):
        try:
            stats, more = fetch_page(site, token, start, offset)
        except urllib.error.HTTPError as err:
            sys.exit("GoatCounter API returned %s: %s" % (err.code, err.read()[:200]))
        countries.extend(s for s in stats if s.get("id"))
        print("fetched %d rows at offset %d" % (len(stats), offset))
        if not more or not stats:
            break
        offset += len(stats)

    countries.sort(key=lambda c: (-c["count"], c["name"]))
    updated = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    write_yaml(os.path.abspath(OUT_PATH), countries, updated)


if __name__ == "__main__":
    main()
